import handlers.achievements_command
import handlers.check_translated_word_correctness
import handlers.get_learning_words
import handlers.set_command
import handlers.start_command
import handlers.stop_command
import handlers.unexpected_messages
