import bot.achievements_command
import bot.create_keyboard_markup
import bot.get_learning_words
import bot.send_random_word
import bot.start_command
import bot.unexpected_messages_reply
import bot.user_response_actions
import bot.user_score
